### PR TITLE
Removing dependency for org.eclipse.equinox.log

### PR DESCRIPTION
**Pull request by stlimtat**
This is just a rough attempt to remove this dependency.  It will allow for the installation of the redmine mylyn into eclipse neon.  I've tested and it's working

### CODE REVIEW

**Comment by sangtraceur** [comment]
Please accept this merge request! Without it it is actually not possible to install the plugin!

**Comment by ljader** [comment]
Hi @stlimtat ,
Thanks for PR.

Did you check how the messages in "net.sf.redmine_mylyn.common/redmine_connector.log" are logged?
Do they have class name associated?

**Comment by stlimtat** [comment]
Nope.  I just wanted a simple good enough hack that runs.  I suspect the process for getting the logs will require that I know more about the logging implementation for eclipse.

**Comment by ljader** [comment]
Hi @stlimtat  , thank you very much for your contribution.

I've cherry-picked few of your commits, however the plugin still uses ExtendedLogService in it's logging logic - but in reworked way as described in commits in PR #77 .

The new 0.5.1 version of plugin has been released in https://github.com/ljader/redmine-mylyn-plugin/releases

Thanks again for the work.

**Pull request closed without merging**
